src/main/java/edu/iit/sat/itmd4515/abhimani/mp2/entities/Student.java
package edu.iit.sat.itmd4515.abhimani.mp2.entities;

import edu.iit.sat.itmd4515.abhimani.mp2.SuperEntityUnit;
import java.io.Serializable;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.Min;
import javax.validation.constraints.Pattern;

/**
 *
 * @author Ankit Bhimani (abhimani) on edu.iit.sat.itmd4515.abhimani.mp2
 */
@Entity
@Table(name = "students")
@NamedQueries({
		@NamedQuery(name = "Students.retrieveAll", query = "SELECT s FROM Student AS s"),
		@NamedQuery(name = "Students.findByNumber", query = "SELECT s FROM Student AS s WHERE s.Student_Number=:Number"),
		@NamedQuery(name = "Students.findByEmailId", query = "SELECT s FROM Student AS s WHERE s.EmailId=:EmailId")})
public class Student extends SuperEntityUnit
		implements
			Comparable<Student>,
			Serializable {
	//COLUMNS
	@Column(name = "Student_Number", nullable = false, length = 36, unique = true, updatable = false)
	private final String Student_Number;

	@Column(name = "FName", nullable = false, length = 255)
	private String FName;

	@Column(name = "LName", nullable = false, length = 255)
	private String LName;

	@Pattern(regexp = "[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\."
			+ "[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@"
			+ "(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", message = "Invalid Email Id.")
	@Column(name = "EmailId", nullable = false, length = 255, unique = true)
	private String EmailId;

	@Column(name = "Gender", nullable = false)
	private char Gender = 'M'; //M, F

	@Column(name = "Phone", nullable = false, length = 10)
	@Min(1000000000)
	private long Phone = 0;

	@Column(name = "NotifyEvents", nullable = false)
	private boolean NotifyEvents;

	@Column(name = "Special", length = 2000)
	private String Special;

	//CONSTRUCTS
	public Student() {
		super();
		this.Student_Number = UUID.randomUUID().toString();
	}

	public Student(String FName, String LName, char Gender, long Phone,
			String EmailId, boolean NotifyEvents, String Special) {
		this.Student_Number = UUID.randomUUID().toString();
		this.FName = FName.trim();
		this.LName = LName.trim();
		this.Gender = Gender;
		this.Phone = Phone;
		this.EmailId = EmailId.trim();
		this.NotifyEvents = NotifyEvents;
		this.Special = Special.trim();
	}

	public Student(String FName, String LName, char Gender, long Phone,
			String EmailId, boolean NotifyEvents) {
		this.Student_Number = UUID.randomUUID().toString();
		this.FName = FName.trim();
		this.LName = LName.trim();
		this.Gender = Gender;
		this.Phone = Phone;
		this.EmailId = EmailId.trim();
		this.NotifyEvents = NotifyEvents;
	}

	//PROPERTIES
	public String getStudent_Number() {
		return Student_Number;
	}

	public String getFName() {
		return FName;
	}

	public void setFName(String FName) {
		this.FName = FName.trim();
	}

	public String getLName() {
		return LName;
	}

	public void setLName(String LName) {
		this.LName = LName.trim();
	}

	public char getGender() {
		return Gender;
	}

	public void setGender(char Gender) {
		this.Gender = Gender;
	}

	public long getPhone() {
		return Phone;
	}

	public void setPhone(long Phone) {
		this.Phone = Phone;
	}

	public String getEmailId() {
		return EmailId;
	}

	public void setEmailId(String EmailId) {
		this.EmailId = EmailId.trim();
	}

	public boolean isNotifyEvents() {
		return NotifyEvents;
	}

	public void setNotifyEvents(boolean NotifyEvents) {
		this.NotifyEvents = NotifyEvents;
	}

	public String getSpecial() {
		return Special;
	}

	public void setSpecial(String Special) {
		this.Special = Special.trim();
	}

	//IMPLEMENTATION
	@Override
	public int compareTo(Student el) {
		return (this.getEmailId().compareTo(el.getEmailId()));
	}

	//OVERRIDES
	@Override
	public boolean equals(Object el) {
		if (!(el instanceof Student))
			return false;
		try {
			Student tstStudent = (Student) el;
			if (!(Integer.compare(this.hashCode(), tstStudent.hashCode()) == 0))
				return false;
		} catch (Exception ex) {
			ex.printStackTrace();
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		try {
			return ("/Entities.Students{Id:"
					+ this.getPid()
					+ ", Number:"
					+ this.getStudent_Number()
					+ ", Name:{First:\""
					+ this.getFName()
					+ "\", Last:\""
					+ this.getLName()
					+ "\"}, Contact:{Phone:"
					+ this.getPhone()
					+ ", EmailId:"
					+ this.getEmailId()
					+ "}, NotifyEvents:"
					+ Boolean.toString(this.isNotifyEvents())
					+ ", Special:{Length:"
					+ ((this.getSpecial() == null) ? 0 : this.getSpecial()
							.length()) + "}}");
		} catch (Exception ex) {
			ex.printStackTrace();
			return ex.toString();
		}
	}
}

src/main/java/edu/iit/sat/itmd4515/abhimani/mp2/view/StudentBean.java
package edu.iit.sat.itmd4515.abhimani.mp2.view;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import javax.ejb.SessionContext;
import javax.ejb.Stateful;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import edu.iit.sat.itmd4515.abhimani.mp2.entities.Student;

/**
 * Backing bean for Student entities.
 * 
 * This class provides CRUD functionality for all Student entities. It focuses
 * purely on Java EE 6 standards (e.g. <tt>&#64;ConversationScoped</tt> for
 * state management, <tt>PersistenceContext</tt> for persistence,
 * <tt>CriteriaBuilder</tt> for searches) rather than introducing a CRUD framework or
 * custom base class.
 */

@Named
@Stateful
@ConversationScoped
public class StudentBean implements Serializable {

	private static final long serialVersionUID = 1L;

	/*
	 * Support creating and retrieving Student entities
	 */

	private Long id;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	private Student student;

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Inject
	private Conversation conversation;

	@PersistenceContext(unitName = "abhimaniPU", type = PersistenceContextType.EXTENDED)
	private EntityManager entityManager;

	public String create() {

		this.conversation.begin();
		this.conversation.setTimeout(1800000L);
		return "create?faces-redirect=true";
	}

	public void retrieve() {

		if (FacesContext.getCurrentInstance().isPostback()) {
			return;
		}

		if (this.conversation.isTransient()) {
			this.conversation.begin();
			this.conversation.setTimeout(1800000L);
		}

		if (this.id == null) {
			this.student = this.example;
		} else {
			this.student = findById(getId());
		}
	}

	public Student findById(Long id) {

		return this.entityManager.find(Student.class, id);
	}

	/*
	 * Support updating and deleting Student entities
	 */

	public String update() {
		this.conversation.end();

		try {
			if (this.id == null) {
				this.entityManager.persist(this.student);
				return "search?faces-redirect=true";
			} else {
				this.entityManager.merge(this.student);
				return "view?faces-redirect=true&id=" + this.student.getId();
			}
		} catch (Exception e) {
			FacesContext.getCurrentInstance().addMessage(null,
					new FacesMessage(e.getMessage()));
			return null;
		}
	}

	public String delete() {
		this.conversation.end();

		try {
			Student deletableEntity = findById(getId());

			this.entityManager.remove(deletableEntity);
			this.entityManager.flush();
			return "search?faces-redirect=true";
		} catch (Exception e) {
			FacesContext.getCurrentInstance().addMessage(null,
					new FacesMessage(e.getMessage()));
			return null;
		}
	}

	/*
	 * Support searching Student entities with pagination
	 */

	private int page;
	private long count;
	private List<Student> pageItems;

	private Student example = new Student();

	public int getPage() {
		return this.page;
	}

	public void setPage(int page) {
		this.page = page;
	}

	public int getPageSize() {
		return 10;
	}

	public Student getExample() {
		return this.example;
	}

	public void setExample(Student example) {
		this.example = example;
	}

	public String search() {
		this.page = 0;
		return null;
	}

	public void paginate() {

		CriteriaBuilder builder = this.entityManager.getCriteriaBuilder();

		// Populate this.count

		CriteriaQuery<Long> countCriteria = builder.createQuery(Long.class);
		Root<Student> root = countCriteria.from(Student.class);
		countCriteria = countCriteria.select(builder.count(root)).where(
				getSearchPredicates(root));
		this.count = this.entityManager.createQuery(countCriteria)
				.getSingleResult();

		// Populate this.pageItems

		CriteriaQuery<Student> criteria = builder.createQuery(Student.class);
		root = criteria.from(Student.class);
		TypedQuery<Student> query = this.entityManager.createQuery(criteria
				.select(root).where(getSearchPredicates(root)));
		query.setFirstResult(this.page * getPageSize()).setMaxResults(
				getPageSize());
		this.pageItems = query.getResultList();
	}

	private Predicate[] getSearchPredicates(Root<Student> root) {

		CriteriaBuilder builder = this.entityManager.getCriteriaBuilder();
		List<Predicate> predicatesList = new ArrayList<Predicate>();

		String FName = this.example.getFName();
		if (FName != null && !"".equals(FName)) {
			predicatesList.add(builder.like(
					builder.lower(root.<String> get("FName")),
					'%' + FName.toLowerCase() + '%'));
		}
		String LName = this.example.getLName();
		if (LName != null && !"".equals(LName)) {
			predicatesList.add(builder.like(
					builder.lower(root.<String> get("LName")),
					'%' + LName.toLowerCase() + '%'));
		}
		long Phone = this.example.getPhone();
		if (Phone != 0) {
			predicatesList.add(builder.equal(root.get("Phone"), Phone));
		}
		String EmailId = this.example.getEmailId();
		if (EmailId != null && !"".equals(EmailId)) {
			predicatesList.add(builder.like(
					builder.lower(root.<String> get("EmailId")),
					'%' + EmailId.toLowerCase() + '%'));
		}
		String Special = this.example.getSpecial();
		if (Special != null && !"".equals(Special)) {
			predicatesList.add(builder.like(
					builder.lower(root.<String> get("Special")),
					'%' + Special.toLowerCase() + '%'));
		}

		return predicatesList.toArray(new Predicate[predicatesList.size()]);
	}

	public List<Student> getPageItems() {
		return this.pageItems;
	}

	public long getCount() {
		return this.count;
	}

	/*
	 * Support listing and POSTing back Student entities (e.g. from inside an
	 * HtmlSelectOneMenu)
	 */

	public List<Student> getAll() {

		CriteriaQuery<Student> criteria = this.entityManager
				.getCriteriaBuilder().createQuery(Student.class);
		return this.entityManager.createQuery(
				criteria.select(criteria.from(Student.class))).getResultList();
	}

	@Resource
	private SessionContext sessionContext;

	public Converter getConverter() {

		final StudentBean ejbProxy = this.sessionContext
				.getBusinessObject(StudentBean.class);

		return new Converter() {

			@Override
			public Object getAsObject(FacesContext context,
					UIComponent component, String value) {

				return ejbProxy.findById(Long.valueOf(value));
			}

			@Override
			public String getAsString(FacesContext context,
					UIComponent component, Object value) {

				if (value == null) {
					return "";
				}

				return String.valueOf(((Student) value).getId());
			}
		};
	}

	/*
	 * Support adding children to bidirectional, one-to-many tables
	 */

	private Student add = new Student();

	public Student getAdd() {
		return this.add;
	}

	public Student getAdded() {
		Student added = this.add;
		this.add = new Student();
		return added;
	}
}

src/main/webapp/student/create.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	template="/resources/scaffold/pageTemplate.xhtml">

	<f:metadata>
		<f:viewParam name="id" value='#{studentBean.id}'/>
		<f:event type="preRenderView" listener='#{studentBean.retrieve}'/>
	</f:metadata>

	<ui:param name="pageTitle" value="Create Student"/>

	<ui:define name="header">
		Student
	</ui:define>

	<ui:define name="subheader">
		<c:choose>
			<c:when test='#{!empty studentBean.id}'>
				Edit existing Student
			</c:when>
			<c:otherwise>
				Create a new Student
			</c:otherwise>
		</c:choose>
	</ui:define>

	<ui:define name="footer"/>

	<ui:define name="main">
		<h:form id="create">
			<h:messages globalOnly="true" styleClass="error"/>

			<h:panelGrid columnClasses="label,component,required" columns="3">
				<h:outputLabel for="studentBeanStudentStudentNumber" value="Student_Number:"/>
				<h:outputText id="studentBeanStudentStudentNumber" value="#{studentBean.student.student_Number}"/>
				<h:outputText/>
				<h:outputLabel for="studentBeanStudentFName" value="F Name:"/>
				<h:panelGroup>
					<h:inputText id="studentBeanStudentFName" required="true" value="#{studentBean.student.FName}"/>
					<h:message for="studentBeanStudentFName" styleClass="error"/>
				</h:panelGroup>
				<h:outputText value="*"/>
				<h:outputLabel for="studentBeanStudentLName" value="L Name:"/>
				<h:panelGroup>
					<h:inputText id="studentBeanStudentLName" required="true" value="#{studentBean.student.LName}"/>
					<h:message for="studentBeanStudentLName" styleClass="error"/>
				</h:panelGroup>
				<h:outputText value="*"/>
				<h:outputLabel for="studentBeanStudentGender" value="Gender:"/>
				<h:panelGroup>
					<h:inputText id="studentBeanStudentGender" maxLength="1" required="true" value="#{studentBean.student.gender}"/>
					<h:message for="studentBeanStudentGender" styleClass="error"/>
				</h:panelGroup>
				<h:outputText value="*"/>
				<h:outputLabel for="studentBeanStudentPhone" value="Phone:"/>
				<h:panelGroup>
					<h:inputText id="studentBeanStudentPhone" maxLength="10" required="true" value="#{studentBean.student.phone}"/>
					<h:message for="studentBeanStudentPhone" styleClass="error"/>
				</h:panelGroup>
				<h:outputText value="*"/>
				<h:outputLabel for="studentBeanStudentEmailId" value="Email Id:"/>
				<h:panelGroup>
					<h:inputText id="studentBeanStudentEmailId" required="true" value="#{studentBean.student.emailId}"/>
					<h:message for="studentBeanStudentEmailId" styleClass="error"/>
				</h:panelGroup>
				<h:outputText value="*"/>
				<h:outputLabel for="studentBeanStudentSpecial" value="Special:"/>
				<h:panelGroup>
					<h:inputTextarea id="studentBeanStudentSpecial" value="#{studentBean.student.special}"/>
					<h:message for="studentBeanStudentSpecial" styleClass="error"/>
				</h:panelGroup>
				<h:outputText/>
				<h:outputLabel for="studentBeanStudentNotifyEvents" value="Notify Events:"/>
				<h:panelGroup>
					<h:selectBooleanCheckbox id="studentBeanStudentNotifyEvents" required="true" value="#{studentBean.student.notifyEvents}"/>
					<h:message for="studentBeanStudentNotifyEvents" styleClass="error"/>
				</h:panelGroup>
				<h:outputText value="*"/>
				<h:outputLabel for="studentBeanStudentPid" value="Pid:"/>
				<h:outputText id="studentBeanStudentPid" value="#{studentBean.student.pid}"/>
				<h:outputText/>
			</h:panelGrid>

			<div class="buttons">
				<h:commandLink value="Save" action='#{studentBean.update}' styleClass="btn btn-primary"/>
				<c:choose>
					<c:when test='#{!empty studentBean.id}'>
						<h:link value="Cancel" outcome="view" styleClass="btn btn-primary">
							<f:param name="id" value='#{studentBean.id}'/>
						</h:link>
						<h:commandLink value="Delete" action='#{studentBean.delete}' styleClass="btn btn-primary"/>
					</c:when>
					<c:otherwise>
						<h:link value="Cancel" outcome="search" styleClass="btn btn-primary"/>
					</c:otherwise>
				</c:choose>
			</div>
		</h:form>
	</ui:define>

</ui:composition>

src/main/webapp/student/search.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/resources/scaffold/pageTemplate.xhtml">

	<f:metadata>
		<f:viewParam name="page" value='#{studentBean.page}'/>
		<f:event type="preRenderView" listener='#{studentBean.paginate}'/>
	</f:metadata>

	<ui:param name="pageTitle" value="Search Student entities"/>

	<ui:define name="header">
		Student
	</ui:define>

	<ui:define name="subheader">
		Search Student entities
	</ui:define>

	<ui:define name="footer"/>

	<ui:define name="main">
		<h:form id="search">
			<f:validateBean disabled="true">
				<h:panelGroup styleClass="search">

					<h:panelGrid columnClasses="label,component,required" columns="3">
						<h:outputLabel for="studentBeanExampleFName" value="F Name:"/>
						<h:panelGroup>
							<h:inputText id="studentBeanExampleFName" value="#{studentBean.example.FName}"/>
							<h:message for="studentBeanExampleFName" styleClass="error"/>
						</h:panelGroup>
						<h:outputText/>
						<h:outputLabel for="studentBeanExampleLName" value="L Name:"/>
						<h:panelGroup>
							<h:inputText id="studentBeanExampleLName" value="#{studentBean.example.LName}"/>
							<h:message for="studentBeanExampleLName" styleClass="error"/>
						</h:panelGroup>
						<h:outputText/>
						<h:outputLabel for="studentBeanExamplePhone" value="Phone:"/>
						<h:panelGroup>
							<h:inputText id="studentBeanExamplePhone" maxLength="10" value="#{studentBean.example.phone}"/>
							<h:message for="studentBeanExamplePhone" styleClass="error"/>
						</h:panelGroup>
						<h:outputText/>
						<h:outputLabel for="studentBeanExampleEmailId" value="Email Id:"/>
						<h:panelGroup>
							<h:inputText id="studentBeanExampleEmailId" value="#{studentBean.example.emailId}"/>
							<h:message for="studentBeanExampleEmailId" styleClass="error"/>
						</h:panelGroup>
						<h:outputText/>
						<h:outputLabel for="studentBeanExampleSpecial" value="Special:"/>
						<h:panelGroup>
							<h:inputTextarea id="studentBeanExampleSpecial" value="#{studentBean.example.special}"/>
							<h:message for="studentBeanExampleSpecial" styleClass="error"/>
						</h:panelGroup>
						<h:outputText/>
					</h:panelGrid>
					<h:panelGroup styleClass="buttons">
						<h:commandLink value="Search" action='#{studentBean.search}' styleClass="btn btn-primary"/>
						<h:commandLink value="Create New" action='#{studentBean.create}' styleClass="btn btn-primary"/>
					</h:panelGroup>
				</h:panelGroup>
			</f:validateBean>
			
			<h:dataTable id="studentBeanPageItems" styleClass="data-table" value="#{studentBean.pageItems}" var="_item">
				<h:column>
					<f:facet name="header">
						<h:outputText value="Student_Number"/>
					</f:facet>
					<h:link outcome="/student/view">
						<f:param name="id" value="#{_item.id}"/>
						<h:outputText id="itemStudentNumber" value="#{_item.student_Number}"/>
					</h:link>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="F Name"/>
					</f:facet>
					<h:link outcome="/student/view">
						<f:param name="id" value="#{_item.id}"/>
						<h:outputText id="itemFName" value="#{_item.FName}"/>
					</h:link>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="L Name"/>
					</f:facet>
					<h:link outcome="/student/view">
						<f:param name="id" value="#{_item.id}"/>
						<h:outputText id="itemLName" value="#{_item.LName}"/>
					</h:link>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Gender"/>
					</f:facet>
					<h:link outcome="/student/view">
						<f:param name="id" value="#{_item.id}"/>
						<h:outputText id="itemGender" value="#{_item.gender}"/>
					</h:link>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Phone"/>
					</f:facet>
					<h:link outcome="/student/view">
						<f:param name="id" value="#{_item.id}"/>
						<h:outputText id="itemPhone" value="#{_item.phone}"/>
					</h:link>
				</h:column>
			</h:dataTable>
			<ui:include src="/resources/scaffold/paginator.xhtml">
				<ui:param name="paginatorBean" value='#{studentBean}'/>
			</ui:include>
		</h:form>
			
	</ui:define>

</ui:composition>

src/main/webapp/student/view.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/resources/scaffold/pageTemplate.xhtml">

	<f:metadata>
		<f:viewParam name="id" value='#{studentBean.id}'/>
		<f:event type="preRenderView" listener='#{studentBean.retrieve}'/>
	</f:metadata>

	<ui:param name="pageTitle" value="View Student"/>

	<ui:define name="header">
		Student
	</ui:define>

	<ui:define name="subheader">
		View existing Student
	</ui:define>

	<ui:define name="footer"/>

	<ui:define name="main">
		<h:panelGrid columnClasses="label,component,required" columns="3">
			<h:outputLabel for="studentBeanStudentStudentNumber" value="Student_Number:"/>
			<h:outputText id="studentBeanStudentStudentNumber" value="#{studentBean.student.student_Number}"/>
			<h:outputText/>
			<h:outputLabel for="studentBeanStudentFName" value="F Name:"/>
			<h:outputText id="studentBeanStudentFName" value="#{studentBean.student.FName}"/>
			<h:outputText/>
			<h:outputLabel for="studentBeanStudentLName" value="L Name:"/>
			<h:outputText id="studentBeanStudentLName" value="#{studentBean.student.LName}"/>
			<h:outputText/>
			<h:outputLabel for="studentBeanStudentGender" value="Gender:"/>
			<h:outputText id="studentBeanStudentGender" value="#{studentBean.student.gender}"/>
			<h:outputText/>
			<h:outputLabel for="studentBeanStudentPhone" value="Phone:"/>
			<h:outputText id="studentBeanStudentPhone" value="#{studentBean.student.phone}"/>
			<h:outputText/>
			<h:outputLabel for="studentBeanStudentEmailId" value="Email Id:"/>
			<h:outputText id="studentBeanStudentEmailId" value="#{studentBean.student.emailId}"/>
			<h:outputText/>
			<h:outputLabel for="studentBeanStudentSpecial" value="Special:"/>
			<h:inputTextarea id="studentBeanStudentSpecial" value="#{studentBean.student.special}"/>
			<h:outputText/>
			<h:outputLabel value="Notify Events:"/>
			<h:outputText styleClass="#{studentBean.student.notifyEvents ? 'boolean-true' : 'boolean-false'}" value=""/>
			<h:outputText/>
			<h:outputLabel for="studentBeanStudentPid" value="Pid:"/>
			<h:outputText id="studentBeanStudentPid" value="#{studentBean.student.pid}"/>
			<h:outputText/>
		</h:panelGrid>

		<div class="buttons">
			<h:link value="View All" outcome="search" styleClass="btn btn-primary"/> 
			<h:link value="Edit" outcome="create" includeViewParams="true" styleClass="btn btn-primary"/>
			<h:link value="Create New" outcome="create" styleClass="btn btn-primary"/>
		</div>
	</ui:define>

</ui:composition>