src/main/java/edu/iit/sat/itmd4515/abhimani/mp2/entities/Venue.java
package edu.iit.sat.itmd4515.abhimani.mp2.entities;

import edu.iit.sat.itmd4515.abhimani.mp2.SuperEntityUnit;
import edu.iit.sat.itmd4515.abhimani.mp2.Venue_Type;
import edu.iit.sat.itmd4515.abhimani.mp2.Country_States;
import java.io.Serializable;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;

/**
 *
 * @author Ankit Bhimani (abhimani) on edu.iit.sat.itmd4515.abhimani.mp2
 */
@Entity
@Table(name = "venues")
@NamedQueries({
		@NamedQuery(name = "Venues.retrieveAll", query = "SELECT v FROM Venue AS v"),
		@NamedQuery(name = "Venues.findByName", query = "SELECT v FROM Venue As v WHERE v.Title=:Name")})
public class Venue extends SuperEntityUnit
		implements
			Comparable<Venue>,
			Serializable {
	//COLUMNS
	@Column(name = "Title", nullable = false, length = 255, unique = true)
	private String Title;

	@Column(name = "Type", nullable = false)
	private Venue_Type Type = Venue_Type.Open;

	@Column(name = "Addr1", nullable = false, length = 255)
	private String Addr1;

	@Column(name = "Addr2", length = 255)
	private String Addr2;

	@Column(name = "City", nullable = false, length = 255)
	private String City;

	@Column(name = "CState", nullable = false, length = 255)
	private Country_States CState;

	@Column(name = "Zip", nullable = false, length = 5)
	@Min(1000)
	@Max(99999)
	private int Zip;

	@Column(name = "Zip_Ext", length = 4)
	@Min(100)
	@Max(9999)
	private int Zip_Ext = 0;

	//CONSTRUCTS
	public Venue() {
		super();
	}

	public Venue(String Title, Venue_Type Type, String Addr1, String Addr2,
			String City, Country_States CState, int Zip, int Zip_Ext) {
		this.Title = Title.trim();
		this.Type = Type;
		this.Addr1 = Addr1.trim();
		this.Addr2 = Addr2.trim();
		this.City = City.trim();
		this.CState = CState;
		this.Zip = Zip;
		this.Zip_Ext = Zip_Ext;
	}

	public Venue(String Title, Venue_Type Type, String Addr1, String City,
			Country_States CState, int Zip) {
		this.Title = Title.trim();
		this.Type = Type;
		this.Addr1 = Addr1.trim();
		this.City = City.trim();
		this.CState = CState;
		this.Zip = Zip;
	}

	//PROPERTIES
	public String getTitle() {
		return Title;
	}

	public void setTitle(String Title) {
		this.Title = Title.trim();
	}

	public String getType() {
		return Type.toString();
	}

	public void setType(Venue_Type Type) {
		this.Type = Type;
	}

	public String getAddr1() {
		return Addr1;
	}

	public void setAddr1(String Addr1) {
		this.Addr1 = Addr1.trim();
	}

	public String getAddr2() {
		return Addr2;
	}

	public void setAddr2(String Addr2) {
		this.Addr2 = Addr2.trim();
	}

	public String getCity() {
		return City;
	}

	public void setCity(String City) {
		this.City = City.trim();
	}

	public String getCState() {
		return CState.toString();
	}

	public void setCState(Country_States CState) {
		this.CState = CState;
	}

	public String getZip() {
		return ((this.Zip_Ext > 0) ? (Zip + "-" + Zip_Ext) : Integer
				.toString(Zip));
	}

	public void setZip(int Zip) {
		this.Zip = Zip;
	}

	public int getZip_Ext() {
		return Zip_Ext;
	}

	public void setZip_Ext(int Ext) {
		this.Zip_Ext = Ext;
	}

	//IMPLEMENTATION
	@Override
	public int compareTo(Venue el) {
		return (this.getTitle().compareTo(el.getTitle()));
	}

	//OVERRIDES
	@Override
	public boolean equals(Object el) {
		if (!(el instanceof Venue))
			return false;
		try {
			Venue tstVenue = (Venue) el;
			if (!(Integer.compare(this.hashCode(), tstVenue.hashCode()) == 0))
				return false;
		} catch (Exception ex) {
			ex.printStackTrace();
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		try {
			return ("/Entities.Venues{Id:" + this.getPid() + ", Title:\""
					+ this.getTitle() + "\", Type:\"" + this.getType()
					+ "\", Address:{Addr1:\"" + this.getAddr1()
					+ "\", Addr2:\""
					+ ((this.getAddr2() == null) ? "" : this.getAddr2())
					+ "\", City:\"" + this.getCity() + "\", State:"
					+ this.getCState() + ", Zip:" + this.getZip() + "}}");
		} catch (Exception ex) {
			ex.printStackTrace();
			return ex.toString();
		}
	}
}

src/main/java/edu/iit/sat/itmd4515/abhimani/mp2/view/VenueBean.java
package edu.iit.sat.itmd4515.abhimani.mp2.view;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import javax.ejb.SessionContext;
import javax.ejb.Stateful;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import edu.iit.sat.itmd4515.abhimani.mp2.entities.Venue;

/**
 * Backing bean for Venue entities.
 * 
 * This class provides CRUD functionality for all Venue entities. It focuses
 * purely on Java EE 6 standards (e.g. <tt>&#64;ConversationScoped</tt> for
 * state management, <tt>PersistenceContext</tt> for persistence,
 * <tt>CriteriaBuilder</tt> for searches) rather than introducing a CRUD
 * framework or custom base class.
 */
@Named
@Stateful
@ConversationScoped
public class VenueBean implements Serializable{

    private static final long serialVersionUID=1L;

    /*
     * Support creating and retrieving Venue entities
     */
    private Long id;

    public Long getId(){
	return this.id;
    }

    public void setId(Long id){
	this.id=id;
    }

    private Venue venue;

    public Venue getVenue(){
	return this.venue;
    }

    public void setVenue(Venue venue){
	this.venue=venue;
    }

    @Inject
    private Conversation conversation;

    @PersistenceContext(unitName="abhimaniPU", type=PersistenceContextType.EXTENDED)
    private EntityManager entityManager;

    public String create(){
	this.conversation.begin();
	this.conversation.setTimeout(1800000L);
	return "create?faces-redirect=true";
    }

    public void retrieve(){
	if(FacesContext.getCurrentInstance().isPostback())
	    return;
	if(this.conversation.isTransient()){
	    this.conversation.begin();
	    this.conversation.setTimeout(1800000L);
	}
	if(this.id==null)
	    this.venue=this.example;
	else
	    this.venue=findById(getId());
    }

    public Venue findById(Long id){
	return this.entityManager.find(Venue.class, id);
    }

    /*
     * Support updating and deleting Venue entities
     */
    public String update(){
	this.conversation.end();
	try{
	    if(this.id==null){
		this.entityManager.persist(this.venue);
		return "search?faces-redirect=true";
	    }else{
		this.entityManager.merge(this.venue);
		return "view?faces-redirect=true&id="+this.venue.getId();
	    }
	}catch(Exception e){
	    FacesContext.getCurrentInstance().addMessage(null,
		    new FacesMessage(e.getMessage()));
	    return null;
	}
    }

    public String delete(){
	this.conversation.end();
	try{
	    Venue deletableEntity=findById(getId());
	    this.entityManager.remove(deletableEntity);
	    this.entityManager.flush();
	    return "search?faces-redirect=true";
	}catch(Exception e){
	    FacesContext.getCurrentInstance().addMessage(null,
		    new FacesMessage(e.getMessage()));
	    return null;
	}
    }

    /*
     * Support searching Venue entities with pagination
     */
    private int page;
    private long count;
    private List<Venue> pageItems;

    private Venue example=new Venue();

    public int getPage(){
	return this.page;
    }

    public void setPage(int page){
	this.page=page;
    }

    public int getPageSize(){
	return 10;
    }

    public Venue getExample(){
	return this.example;
    }

    public void setExample(Venue example){
	this.example=example;
    }

    public String search(){
	this.page=0;
	return null;
    }

    public void paginate(){
	CriteriaBuilder builder=this.entityManager.getCriteriaBuilder();
		// Populate this.count
	CriteriaQuery<Long> countCriteria=builder.createQuery(Long.class);
	Root<Venue> root=countCriteria.from(Venue.class);
	countCriteria=countCriteria.select(builder.count(root)).where(
		getSearchPredicates(root));
	this.count=this.entityManager.createQuery(countCriteria)
		.getSingleResult();
		// Populate this.pageItems
	CriteriaQuery<Venue> criteria=builder.createQuery(Venue.class);
	root=criteria.from(Venue.class);
	TypedQuery<Venue> query=this.entityManager.createQuery(criteria
		.select(root).where(getSearchPredicates(root)));
	query.setFirstResult(this.page*getPageSize()).setMaxResults(
		getPageSize());
	this.pageItems=query.getResultList();
    }

    private Predicate[] getSearchPredicates(Root<Venue> root){
	CriteriaBuilder builder=this.entityManager.getCriteriaBuilder();
	List<Predicate> predicatesList=new ArrayList<Predicate>();
	String Title=this.example.getTitle();
	if(Title!=null&&!"".equals(Title))
	    predicatesList.add(builder.like(
		    builder.lower(root.<String>get("Title")),
		    '%'+Title.toLowerCase()+'%'));
	String Type=this.example.getType();
	if(Type!=null&&!"".equals(Type))
	    predicatesList.add(builder.like(
		    builder.lower(root.<String>get("Type")),
		    '%'+Type.toLowerCase()+'%'));
	String Addr1=this.example.getAddr1();
	if(Addr1!=null&&!"".equals(Addr1))
	    predicatesList.add(builder.like(
		    builder.lower(root.<String>get("Addr1")),
		    '%'+Addr1.toLowerCase()+'%'));
	String Addr2=this.example.getAddr2();
	if(Addr2!=null&&!"".equals(Addr2))
	    predicatesList.add(builder.like(
		    builder.lower(root.<String>get("Addr2")),
		    '%'+Addr2.toLowerCase()+'%'));
	String City=this.example.getCity();
	if(City!=null&&!"".equals(City))
	    predicatesList.add(builder.like(
		    builder.lower(root.<String>get("City")),
		    '%'+City.toLowerCase()+'%'));
	return predicatesList.toArray(new Predicate[predicatesList.size()]);
    }

    public List<Venue> getPageItems(){
	return this.pageItems;
    }

    public long getCount(){
	return this.count;
    }

    /*
     * Support listing and POSTing back Venue entities (e.g. from inside an
     * HtmlSelectOneMenu)
     */
    public List<Venue> getAll(){
	CriteriaQuery<Venue> criteria=this.entityManager.getCriteriaBuilder()
		.createQuery(Venue.class);
	return this.entityManager.createQuery(
		criteria.select(criteria.from(Venue.class))).getResultList();
    }

    @Resource
    private SessionContext sessionContext;

    public Converter getConverter(){
	final VenueBean ejbProxy=this.sessionContext
		.getBusinessObject(VenueBean.class);
	return new Converter(){
	    @Override
	    public Object getAsObject(FacesContext context,
		    UIComponent component, String value){
		return ejbProxy.findById(Long.valueOf(value));
	    }

	    @Override
	    public String getAsString(FacesContext context,
		    UIComponent component, Object value){
		if(value==null)
		    return "";
		return String.valueOf(((Venue)value).getId());
	    }
	};
    }

    /*
     * Support adding children to bidirectional, one-to-many tables
     */
    private Venue add=new Venue();

    public Venue getAdd(){
	return this.add;
    }

    public Venue getAdded(){
	Venue added=this.add;
	this.add=new Venue();
	return added;
    }
}

src/main/webapp/venue/create.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	template="/resources/scaffold/pageTemplate.xhtml">

	<f:metadata>
		<f:viewParam name="id" value='#{venueBean.id}'/>
		<f:event type="preRenderView" listener='#{venueBean.retrieve}'/>
	</f:metadata>

	<ui:param name="pageTitle" value="Create Venue"/>

	<ui:define name="header">
		Venue
	</ui:define>

	<ui:define name="subheader">
		<c:choose>
			<c:when test='#{!empty venueBean.id}'>
				Edit existing Venue
			</c:when>
			<c:otherwise>
				Create a new Venue
			</c:otherwise>
		</c:choose>
	</ui:define>

	<ui:define name="footer"/>

	<ui:define name="main">
		<h:form id="create">
			<h:messages globalOnly="true" styleClass="error"/>

			<h:panelGrid columnClasses="label,component,required" columns="3">
				<h:outputLabel for="venueBeanVenueTitle" value="Title:"/>
				<h:panelGroup>
					<h:inputText id="venueBeanVenueTitle" required="true" value="#{venueBean.venue.title}"/>
					<h:message for="venueBeanVenueTitle" styleClass="error"/>
				</h:panelGroup>
				<h:outputText value="*"/>
				<h:outputLabel for="venueBeanVenueType" value="Type:"/>
				<h:panelGroup>
					<h:inputText id="venueBeanVenueType" required="true" value="#{venueBean.venue.type}"/>
					<h:message for="venueBeanVenueType" styleClass="error"/>
				</h:panelGroup>
				<h:outputText value="*"/>
				<h:outputLabel for="venueBeanVenueAddr1" value="Addr 1:"/>
				<h:panelGroup>
					<h:inputText id="venueBeanVenueAddr1" required="true" value="#{venueBean.venue.addr1}"/>
					<h:message for="venueBeanVenueAddr1" styleClass="error"/>
				</h:panelGroup>
				<h:outputText value="*"/>
				<h:outputLabel for="venueBeanVenueAddr2" value="Addr 2:"/>
				<h:panelGroup>
					<h:inputText id="venueBeanVenueAddr2" value="#{venueBean.venue.addr2}"/>
					<h:message for="venueBeanVenueAddr2" styleClass="error"/>
				</h:panelGroup>
				<h:outputText/>
				<h:outputLabel for="venueBeanVenueCity" value="City:"/>
				<h:panelGroup>
					<h:inputText id="venueBeanVenueCity" required="true" value="#{venueBean.venue.city}"/>
					<h:message for="venueBeanVenueCity" styleClass="error"/>
				</h:panelGroup>
				<h:outputText value="*"/>
				<h:outputLabel for="venueBeanVenueCState" value="C State:"/>
				<h:panelGroup>
					<h:inputText id="venueBeanVenueCState" required="true" value="#{venueBean.venue.CState}"/>
					<h:message for="venueBeanVenueCState" styleClass="error"/>
				</h:panelGroup>
				<h:outputText value="*"/>
				<h:outputLabel for="venueBeanVenueZip" value="Zip:"/>
				<h:panelGroup>
					<h:inputText id="venueBeanVenueZip" maxLength="5" required="true" value="#{venueBean.venue.zip}"/>
					<h:message for="venueBeanVenueZip" styleClass="error"/>
				</h:panelGroup>
				<h:outputText value="*"/>
				<h:outputLabel for="venueBeanVenueZipExt" value="Zip_Ext:"/>
				<h:panelGroup>
					<h:inputText id="venueBeanVenueZipExt" maxLength="4" value="#{venueBean.venue.zip_Ext}"/>
					<h:message for="venueBeanVenueZipExt" styleClass="error"/>
				</h:panelGroup>
				<h:outputText/>
				<h:outputLabel for="venueBeanVenuePid" value="Pid:"/>
				<h:outputText id="venueBeanVenuePid" value="#{venueBean.venue.pid}"/>
				<h:outputText/>
			</h:panelGrid>

			<div class="buttons">
				<h:commandLink value="Save" action='#{venueBean.update}' styleClass="btn btn-primary"/>
				<c:choose>
					<c:when test='#{!empty venueBean.id}'>
						<h:link value="Cancel" outcome="view" styleClass="btn btn-primary">
							<f:param name="id" value='#{venueBean.id}'/>
						</h:link>
						<h:commandLink value="Delete" action='#{venueBean.delete}' styleClass="btn btn-primary"/>
					</c:when>
					<c:otherwise>
						<h:link value="Cancel" outcome="search" styleClass="btn btn-primary"/>
					</c:otherwise>
				</c:choose>
			</div>
		</h:form>
	</ui:define>

</ui:composition>

src/main/webapp/venue/search.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/resources/scaffold/pageTemplate.xhtml">

	<f:metadata>
		<f:viewParam name="page" value='#{venueBean.page}'/>
		<f:event type="preRenderView" listener='#{venueBean.paginate}'/>
	</f:metadata>

	<ui:param name="pageTitle" value="Search Venue entities"/>

	<ui:define name="header">
		Venue
	</ui:define>

	<ui:define name="subheader">
		Search Venue entities
	</ui:define>

	<ui:define name="footer"/>

	<ui:define name="main">
		<h:form id="search">
			<f:validateBean disabled="true">
				<h:panelGroup styleClass="search">

					<h:panelGrid columnClasses="label,component,required" columns="3">
						<h:outputLabel for="venueBeanExampleTitle" value="Title:"/>
						<h:panelGroup>
							<h:inputText id="venueBeanExampleTitle" value="#{venueBean.example.title}"/>
							<h:message for="venueBeanExampleTitle" styleClass="error"/>
						</h:panelGroup>
						<h:outputText/>
						<h:outputLabel for="venueBeanExampleType" value="Type:"/>
						<h:panelGroup>
							<h:inputText id="venueBeanExampleType" value="#{venueBean.example.type}"/>
							<h:message for="venueBeanExampleType" styleClass="error"/>
						</h:panelGroup>
						<h:outputText/>
						<h:outputLabel for="venueBeanExampleAddr1" value="Addr 1:"/>
						<h:panelGroup>
							<h:inputText id="venueBeanExampleAddr1" value="#{venueBean.example.addr1}"/>
							<h:message for="venueBeanExampleAddr1" styleClass="error"/>
						</h:panelGroup>
						<h:outputText/>
						<h:outputLabel for="venueBeanExampleAddr2" value="Addr 2:"/>
						<h:panelGroup>
							<h:inputText id="venueBeanExampleAddr2" value="#{venueBean.example.addr2}"/>
							<h:message for="venueBeanExampleAddr2" styleClass="error"/>
						</h:panelGroup>
						<h:outputText/>
						<h:outputLabel for="venueBeanExampleCity" value="City:"/>
						<h:panelGroup>
							<h:inputText id="venueBeanExampleCity" value="#{venueBean.example.city}"/>
							<h:message for="venueBeanExampleCity" styleClass="error"/>
						</h:panelGroup>
						<h:outputText/>
					</h:panelGrid>
					<h:panelGroup styleClass="buttons">
						<h:commandLink value="Search" action='#{venueBean.search}' styleClass="btn btn-primary"/>
						<h:commandLink value="Create New" action='#{venueBean.create}' styleClass="btn btn-primary"/>
					</h:panelGroup>
				</h:panelGroup>
			</f:validateBean>
			
			<h:dataTable id="venueBeanPageItems" styleClass="data-table" value="#{venueBean.pageItems}" var="_item">
				<h:column>
					<f:facet name="header">
						<h:outputText value="Title"/>
					</f:facet>
					<h:link outcome="/venue/view">
						<f:param name="id" value="#{_item.id}"/>
						<h:outputText id="itemTitle" value="#{_item.title}"/>
					</h:link>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Type"/>
					</f:facet>
					<h:link outcome="/venue/view">
						<f:param name="id" value="#{_item.id}"/>
						<h:outputText id="itemType" value="#{_item.type}"/>
					</h:link>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Addr 1"/>
					</f:facet>
					<h:link outcome="/venue/view">
						<f:param name="id" value="#{_item.id}"/>
						<h:outputText id="itemAddr1" value="#{_item.addr1}"/>
					</h:link>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="City"/>
					</f:facet>
					<h:link outcome="/venue/view">
						<f:param name="id" value="#{_item.id}"/>
						<h:outputText id="itemCity" value="#{_item.city}"/>
					</h:link>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="C State"/>
					</f:facet>
					<h:link outcome="/venue/view">
						<f:param name="id" value="#{_item.id}"/>
						<h:outputText id="itemCState" value="#{_item.CState}"/>
					</h:link>
				</h:column>
			</h:dataTable>
			<ui:include src="/resources/scaffold/paginator.xhtml">
				<ui:param name="paginatorBean" value='#{venueBean}'/>
			</ui:include>
		</h:form>
			
	</ui:define>

</ui:composition>

src/main/webapp/venue/view.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/resources/scaffold/pageTemplate.xhtml">

	<f:metadata>
		<f:viewParam name="id" value='#{venueBean.id}'/>
		<f:event type="preRenderView" listener='#{venueBean.retrieve}'/>
	</f:metadata>

	<ui:param name="pageTitle" value="View Venue"/>

	<ui:define name="header">
		Venue
	</ui:define>

	<ui:define name="subheader">
		View existing Venue
	</ui:define>

	<ui:define name="footer"/>

	<ui:define name="main">
		<h:panelGrid columnClasses="label,component,required" columns="3">
			<h:outputLabel for="venueBeanVenueTitle" value="Title:"/>
			<h:outputText id="venueBeanVenueTitle" value="#{venueBean.venue.title}"/>
			<h:outputText/>
			<h:outputLabel for="venueBeanVenueType" value="Type:"/>
			<h:outputText id="venueBeanVenueType" value="#{venueBean.venue.type}"/>
			<h:outputText/>
			<h:outputLabel for="venueBeanVenueAddr1" value="Addr 1:"/>
			<h:outputText id="venueBeanVenueAddr1" value="#{venueBean.venue.addr1}"/>
			<h:outputText/>
			<h:outputLabel for="venueBeanVenueAddr2" value="Addr 2:"/>
			<h:outputText id="venueBeanVenueAddr2" value="#{venueBean.venue.addr2}"/>
			<h:outputText/>
			<h:outputLabel for="venueBeanVenueCity" value="City:"/>
			<h:outputText id="venueBeanVenueCity" value="#{venueBean.venue.city}"/>
			<h:outputText/>
			<h:outputLabel for="venueBeanVenueCState" value="C State:"/>
			<h:outputText id="venueBeanVenueCState" value="#{venueBean.venue.CState}"/>
			<h:outputText/>
			<h:outputLabel for="venueBeanVenueZip" value="Zip:"/>
			<h:outputText id="venueBeanVenueZip" value="#{venueBean.venue.zip}"/>
			<h:outputText/>
			<h:outputLabel for="venueBeanVenueZipExt" value="Zip_Ext:"/>
			<h:outputText id="venueBeanVenueZipExt" value="#{venueBean.venue.zip_Ext}"/>
			<h:outputText/>
			<h:outputLabel for="venueBeanVenuePid" value="Pid:"/>
			<h:outputText id="venueBeanVenuePid" value="#{venueBean.venue.pid}"/>
			<h:outputText/>
		</h:panelGrid>

		<div class="buttons">
			<h:link value="View All" outcome="search" styleClass="btn btn-primary"/> 
			<h:link value="Edit" outcome="create" includeViewParams="true" styleClass="btn btn-primary"/>
			<h:link value="Create New" outcome="create" styleClass="btn btn-primary"/>
		</div>
	</ui:define>

</ui:composition>