src/main/java/edu/iit/sat/itmd4515/abhimani/mp2/entities/Event.java
package edu.iit.sat.itmd4515.abhimani.mp2.entities;

import edu.iit.sat.itmd4515.abhimani.mp2.SuperEntityUnit;
import edu.iit.sat.itmd4515.abhimani.mp2.EventState;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 *
 * @author Ankit Bhimani (abhimani) on edu.iit.sat.itmd4515.abhimani.mp2
 */
@Entity
@Table(name = "event_store")
@NamedQueries({
		@NamedQuery(name = "Events.retrieveAll", query = "SELECT e FROM Event AS e"),
		@NamedQuery(name = "Events.findById", query = "SELECT e FROM Event AS e WHERE e.PId=:EventId")})
public class Event extends SuperEntityUnit
		implements
			Comparable<Event>,
			Serializable {
	//COLUMNS
	@Column(name = "Title", nullable = false, length = 255, unique = true)
	private String Title;

	@Column(name = "Description", length = 2000)
	private String Description;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EBegin", nullable = false)
	private Date EBegin;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EEnd", nullable = false)
	private Date EEnd;

	@Column(name = "AState", nullable = false)
	private EventState AState = EventState.Active;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CDate", nullable = false, insertable = true, updatable = false, columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
	private Date CDate = new Date();

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MDate", insertable = false, updatable = true, columnDefinition = "TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
	private Date MDate;

	//CONSTRUCTS
	public Event() {
		super();
	}

	public Event(String Title, String Description, Date EBegin, Date EEnd) {
		this.Title = Title.trim();
		this.Description = Description.trim();
		this.EBegin = EBegin;
		this.EEnd = EEnd;
	}

	public Event(String Title, String Description, Date EBegin, Date EEnd,
			EventState AState) {
		this.Title = Title.trim();
		this.Description = Description.trim();
		this.EBegin = EBegin;
		this.EEnd = EEnd;
		this.AState = AState;
	}

	//PROPERTIES
	public String getTitle() {
		return Title;
	}

	public void setTitle(String Title) {
		this.Title = Title.trim();
	}

	public String getDescription() {
		return Description;
	}

	public void setDescription(String Description) {
		this.Description = Description.trim();
	}

	public String getEBegin() {
		return EBegin.toString();
	}

	public void setEBegin(Date EBegin) {
		this.EBegin = EBegin;
	}

	public String getEEnd() {
		return EEnd.toString();
	}

	public void setEEnd(Date EEnd) {
		this.EEnd = EEnd;
	}

	public String getAState() {
		return AState.toString();
	}

	public void setAState(EventState AState) {
		this.AState = AState;
	}

	public String getCDate() {
		return CDate.toString();
	}

	public String getMDate() {
		return ((MDate == null) ? "-" : MDate.toString());
	}

	//IMPLEMENTATION
	@Override
	public int compareTo(Event el) {
		return (this.getTitle().compareTo(el.getTitle()));
	}

	//OVERRIDES
	@Override
	public boolean equals(Object el) {
		if (!(el instanceof Event))
			return false;
		try {
			Event tstEvt = (Event) el;
			if (!(Integer.compare(this.hashCode(), tstEvt.hashCode()) == 0))
				return false;
		} catch (Exception ex) {
			ex.printStackTrace();
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		try {
			return ("/Entities.Events{Id:"
					+ this.getPid()
					+ ", Title:\""
					+ this.getTitle()
					+ "\", Description:{Length:"
					+ ((this.getDescription() == null) ? 0 : this
							.getDescription().length()) + "}, EBegin:\""
					+ this.getEBegin() + "\", EEnd:\"" + this.getEEnd()
					+ "\", State:" + this.getAState().toUpperCase()
					+ ", Create_Date:\"" + this.getCDate()
					+ "\", Last_Modified:\"" + this.getMDate() + "\"}");
		} catch (Exception ex) {
			ex.printStackTrace();
			return ex.toString();
		}
	}
}

src/main/java/edu/iit/sat/itmd4515/abhimani/mp2/view/EventBean.java
package edu.iit.sat.itmd4515.abhimani.mp2.view;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import javax.ejb.SessionContext;
import javax.ejb.Stateful;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import edu.iit.sat.itmd4515.abhimani.mp2.entities.Event;

/**
 * Backing bean for Event entities.
 * 
 * This class provides CRUD functionality for all Event entities. It focuses
 * purely on Java EE 6 standards (e.g. <tt>&#64;ConversationScoped</tt> for
 * state management, <tt>PersistenceContext</tt> for persistence,
 * <tt>CriteriaBuilder</tt> for searches) rather than introducing a CRUD
 * framework or custom base class.
 */
@Named
@Stateful
@ConversationScoped
public class EventBean implements Serializable{

    private static final long serialVersionUID=1L;

    /*
     * Support creating and retrieving Event entities
     */
    private Long id;

    public Long getId(){
	return this.id;
    }

    public void setId(Long id){
	this.id=id;
    }

    private Event event;

    public Event getEvent(){
	return this.event;
    }

    public void setEvent(Event event){
	this.event=event;
    }

    @Inject
    private Conversation conversation;

    @PersistenceContext(unitName="abhimaniPU", type=PersistenceContextType.EXTENDED)
    private EntityManager entityManager;

    public String create(){
	this.conversation.begin();
	this.conversation.setTimeout(1800000L);
	return "create?faces-redirect=true";
    }

    public void retrieve(){
	if(FacesContext.getCurrentInstance().isPostback())
	    return;
	if(this.conversation.isTransient()){
	    this.conversation.begin();
	    this.conversation.setTimeout(1800000L);
	}
	if(this.id==null)
	    this.event=this.example;
	else
	    this.event=findById(getId());
    }

    public Event findById(Long id){
	return this.entityManager.find(Event.class, id);
    }

    /*
     * Support updating and deleting Event entities
     */
    public String update(){
	this.conversation.end();
	try{
	    if(this.id==null){
		this.entityManager.persist(this.event);
		return "search?faces-redirect=true";
	    }else{
		this.entityManager.merge(this.event);
		return "view?faces-redirect=true&id="+this.event.getId();
	    }
	}catch(Exception e){
	    FacesContext.getCurrentInstance().addMessage(null,
		    new FacesMessage(e.getMessage()));
	    return null;
	}
    }

    public String delete(){
	this.conversation.end();
	try{
	    Event deletableEntity=findById(getId());
	    this.entityManager.remove(deletableEntity);
	    this.entityManager.flush();
	    return "search?faces-redirect=true";
	}catch(Exception e){
	    FacesContext.getCurrentInstance().addMessage(null,
		    new FacesMessage(e.getMessage()));
	    return null;
	}
    }

    /*
     * Support searching Event entities with pagination
     */
    private int page;
    private long count;
    private List<Event> pageItems;

    private Event example=new Event();

    public int getPage(){
	return this.page;
    }

    public void setPage(int page){
	this.page=page;
    }

    public int getPageSize(){
	return 10;
    }

    public Event getExample(){
	return this.example;
    }

    public void setExample(Event example){
	this.example=example;
    }

    public String search(){
	this.page=0;
	return null;
    }

    public void paginate(){
	CriteriaBuilder builder=this.entityManager.getCriteriaBuilder();
		// Populate this.count
	CriteriaQuery<Long> countCriteria=builder.createQuery(Long.class);
	Root<Event> root=countCriteria.from(Event.class);
	countCriteria=countCriteria.select(builder.count(root)).where(
		getSearchPredicates(root));
	this.count=this.entityManager.createQuery(countCriteria)
		.getSingleResult();
		// Populate this.pageItems
	CriteriaQuery<Event> criteria=builder.createQuery(Event.class);
	root=criteria.from(Event.class);
	TypedQuery<Event> query=this.entityManager.createQuery(criteria
		.select(root).where(getSearchPredicates(root)));
	query.setFirstResult(this.page*getPageSize()).setMaxResults(
		getPageSize());
	this.pageItems=query.getResultList();
    }

    private Predicate[] getSearchPredicates(Root<Event> root){
	CriteriaBuilder builder=this.entityManager.getCriteriaBuilder();
	List<Predicate> predicatesList=new ArrayList<Predicate>();
	String Title=this.example.getTitle();
	if(Title!=null&&!"".equals(Title))
	    predicatesList.add(builder.like(
		    builder.lower(root.<String>get("Title")),
		    '%'+Title.toLowerCase()+'%'));
	String Description=this.example.getDescription();
	if(Description!=null&&!"".equals(Description))
	    predicatesList.add(builder.like(
		    builder.lower(root.<String>get("Description")),
		    '%'+Description.toLowerCase()+'%'));
	String EBegin=this.example.getEBegin();
	if(EBegin!=null&&!"".equals(EBegin))
	    predicatesList.add(builder.like(
		    builder.lower(root.<String>get("EBegin")),
		    '%'+EBegin.toLowerCase()+'%'));
	String EEnd=this.example.getEEnd();
	if(EEnd!=null&&!"".equals(EEnd))
	    predicatesList.add(builder.like(
		    builder.lower(root.<String>get("EEnd")),
		    '%'+EEnd.toLowerCase()+'%'));
	String AState=this.example.getAState();
	if(AState!=null&&!"".equals(AState))
	    predicatesList.add(builder.like(
		    builder.lower(root.<String>get("AState")),
		    '%'+AState.toLowerCase()+'%'));
	return predicatesList.toArray(new Predicate[predicatesList.size()]);
    }

    public List<Event> getPageItems(){
	return this.pageItems;
    }

    public long getCount(){
	return this.count;
    }

    /*
     * Support listing and POSTing back Event entities (e.g. from inside an
     * HtmlSelectOneMenu)
     */
    public List<Event> getAll(){
	CriteriaQuery<Event> criteria=this.entityManager.getCriteriaBuilder()
		.createQuery(Event.class);
	return this.entityManager.createQuery(
		criteria.select(criteria.from(Event.class))).getResultList();
    }

    @Resource
    private SessionContext sessionContext;

    public Converter getConverter(){
	final EventBean ejbProxy=this.sessionContext
		.getBusinessObject(EventBean.class);
	return new Converter(){
	    @Override
	    public Object getAsObject(FacesContext context,
		    UIComponent component, String value){
		return ejbProxy.findById(Long.valueOf(value));
	    }

	    @Override
	    public String getAsString(FacesContext context,
		    UIComponent component, Object value){
		if(value==null)
		    return "";
		return String.valueOf(((Event)value).getId());
	    }
	};
    }

    /*
     * Support adding children to bidirectional, one-to-many tables
     */
    private Event add=new Event();

    public Event getAdd(){
	return this.add;
    }

    public Event getAdded(){
	Event added=this.add;
	this.add=new Event();
	return added;
    }
}

src/main/webapp/event/create.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	template="/resources/scaffold/pageTemplate.xhtml">

	<f:metadata>
		<f:viewParam name="id" value='#{eventBean.id}'/>
		<f:event type="preRenderView" listener='#{eventBean.retrieve}'/>
	</f:metadata>

	<ui:param name="pageTitle" value="Create Event"/>

	<ui:define name="header">
		Event
	</ui:define>

	<ui:define name="subheader">
		<c:choose>
			<c:when test='#{!empty eventBean.id}'>
				Edit existing Event
			</c:when>
			<c:otherwise>
				Create a new Event
			</c:otherwise>
		</c:choose>
	</ui:define>

	<ui:define name="footer"/>

	<ui:define name="main">
		<h:form id="create">
			<h:messages globalOnly="true" styleClass="error"/>

			<h:panelGrid columnClasses="label,component,required" columns="3">
				<h:outputLabel for="eventBeanEventTitle" value="Title:"/>
				<h:panelGroup>
					<h:inputText id="eventBeanEventTitle" required="true" value="#{eventBean.event.title}"/>
					<h:message for="eventBeanEventTitle" styleClass="error"/>
				</h:panelGroup>
				<h:outputText value="*"/>
				<h:outputLabel for="eventBeanEventDescription" value="Description:"/>
				<h:panelGroup>
					<h:inputTextarea id="eventBeanEventDescription" value="#{eventBean.event.description}"/>
					<h:message for="eventBeanEventDescription" styleClass="error"/>
				</h:panelGroup>
				<h:outputText/>
				<h:outputLabel for="eventBeanEventEBegin" value="E Begin:"/>
				<h:panelGroup>
					<h:inputText id="eventBeanEventEBegin" required="true" value="#{eventBean.event.EBegin}">
						<f:convertDateTime pattern="MMM d, yyyy hh:mm:ss a" type="both"/>
					</h:inputText>
					<h:message for="eventBeanEventEBegin" styleClass="error"/>
				</h:panelGroup>
				<h:outputText value="*"/>
				<h:outputLabel for="eventBeanEventEEnd" value="E End:"/>
				<h:panelGroup>
					<h:inputText id="eventBeanEventEEnd" required="true" value="#{eventBean.event.EEnd}">
						<f:convertDateTime pattern="MMM d, yyyy hh:mm:ss a" type="both"/>
					</h:inputText>
					<h:message for="eventBeanEventEEnd" styleClass="error"/>
				</h:panelGroup>
				<h:outputText value="*"/>
				<h:outputLabel for="eventBeanEventAState" value="A State:"/>
				<h:panelGroup>
					<h:inputText id="eventBeanEventAState" required="true" value="#{eventBean.event.AState}"/>
					<h:message for="eventBeanEventAState" styleClass="error"/>
				</h:panelGroup>
				<h:outputText value="*"/>
				<h:outputLabel for="eventBeanEventCDate" value="C Date:"/>
				<h:outputText id="eventBeanEventCDate" value="#{eventBean.event.CDate}">
					<f:convertDateTime pattern="MMM d, yyyy hh:mm:ss a" type="both"/>
				</h:outputText>
				<h:outputText/>
				<h:outputLabel for="eventBeanEventMDate" value="M Date:"/>
				<h:outputText id="eventBeanEventMDate" value="#{eventBean.event.MDate}">
					<f:convertDateTime pattern="MMM d, yyyy hh:mm:ss a" type="both"/>
				</h:outputText>
				<h:outputText/>
				<h:outputLabel for="eventBeanEventPid" value="Pid:"/>
				<h:outputText id="eventBeanEventPid" value="#{eventBean.event.pid}"/>
				<h:outputText/>
			</h:panelGrid>

			<div class="buttons">
				<h:commandLink value="Save" action='#{eventBean.update}' styleClass="btn btn-primary"/>
				<c:choose>
					<c:when test='#{!empty eventBean.id}'>
						<h:link value="Cancel" outcome="view" styleClass="btn btn-primary">
							<f:param name="id" value='#{eventBean.id}'/>
						</h:link>
						<h:commandLink value="Delete" action='#{eventBean.delete}' styleClass="btn btn-primary"/>
					</c:when>
					<c:otherwise>
						<h:link value="Cancel" outcome="search" styleClass="btn btn-primary"/>
					</c:otherwise>
				</c:choose>
			</div>
		</h:form>
	</ui:define>

</ui:composition>

src/main/webapp/event/search.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/resources/scaffold/pageTemplate.xhtml">

	<f:metadata>
		<f:viewParam name="page" value='#{eventBean.page}'/>
		<f:event type="preRenderView" listener='#{eventBean.paginate}'/>
	</f:metadata>

	<ui:param name="pageTitle" value="Search Event entities"/>

	<ui:define name="header">
		Event
	</ui:define>

	<ui:define name="subheader">
		Search Event entities
	</ui:define>

	<ui:define name="footer"/>

	<ui:define name="main">
		<h:form id="search">
			<f:validateBean disabled="true">
				<h:panelGroup styleClass="search">

					<h:panelGrid columnClasses="label,component,required" columns="3">
						<h:outputLabel for="eventBeanExampleTitle" value="Title:"/>
						<h:panelGroup>
							<h:inputText id="eventBeanExampleTitle" value="#{eventBean.example.title}"/>
							<h:message for="eventBeanExampleTitle" styleClass="error"/>
						</h:panelGroup>
						<h:outputText/>
						<h:outputLabel for="eventBeanExampleDescription" value="Description:"/>
						<h:panelGroup>
							<h:inputTextarea id="eventBeanExampleDescription" value="#{eventBean.example.description}"/>
							<h:message for="eventBeanExampleDescription" styleClass="error"/>
						</h:panelGroup>
						<h:outputText/>
						<h:outputLabel for="eventBeanExampleEBegin" value="E Begin:"/>
						<h:panelGroup>
							<h:inputText id="eventBeanExampleEBegin" value="#{eventBean.example.EBegin}">
								<f:convertDateTime type="both"/>
							</h:inputText>
							<h:message for="eventBeanExampleEBegin" styleClass="error"/>
						</h:panelGroup>
						<h:outputText/>
						<h:outputLabel for="eventBeanExampleEEnd" value="E End:"/>
						<h:panelGroup>
							<h:inputText id="eventBeanExampleEEnd" value="#{eventBean.example.EEnd}">
								<f:convertDateTime type="both"/>
							</h:inputText>
							<h:message for="eventBeanExampleEEnd" styleClass="error"/>
						</h:panelGroup>
						<h:outputText/>
						<h:outputLabel for="eventBeanExampleAState" value="A State:"/>
						<h:panelGroup>
							<h:inputText id="eventBeanExampleAState" value="#{eventBean.example.AState}"/>
							<h:message for="eventBeanExampleAState" styleClass="error"/>
						</h:panelGroup>
						<h:outputText/>
					</h:panelGrid>
					<h:panelGroup styleClass="buttons">
						<h:commandLink value="Search" action='#{eventBean.search}' styleClass="btn btn-primary"/>
						<h:commandLink value="Create New" action='#{eventBean.create}' styleClass="btn btn-primary"/>
					</h:panelGroup>
				</h:panelGroup>
			</f:validateBean>
			
			<h:dataTable id="eventBeanPageItems" styleClass="data-table" value="#{eventBean.pageItems}" var="_item">
				<h:column>
					<f:facet name="header">
						<h:outputText value="Title"/>
					</f:facet>
					<h:link outcome="/event/view">
						<f:param name="id" value="#{_item.id}"/>
						<h:outputText id="itemTitle" value="#{_item.title}"/>
					</h:link>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="E Begin"/>
					</f:facet>
					<h:link outcome="/event/view">
						<f:param name="id" value="#{_item.id}"/>
						<h:outputText id="itemEBegin" value="#{_item.EBegin}">
							<f:convertDateTime type="both"/>
						</h:outputText>
					</h:link>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="E End"/>
					</f:facet>
					<h:link outcome="/event/view">
						<f:param name="id" value="#{_item.id}"/>
						<h:outputText id="itemEEnd" value="#{_item.EEnd}">
							<f:convertDateTime type="both"/>
						</h:outputText>
					</h:link>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="A State"/>
					</f:facet>
					<h:link outcome="/event/view">
						<f:param name="id" value="#{_item.id}"/>
						<h:outputText id="itemAState" value="#{_item.AState}"/>
					</h:link>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="C Date"/>
					</f:facet>
					<h:link outcome="/event/view">
						<f:param name="id" value="#{_item.id}"/>
						<h:outputText id="itemCDate" value="#{_item.CDate}">
							<f:convertDateTime type="both"/>
						</h:outputText>
					</h:link>
				</h:column>
			</h:dataTable>
			<ui:include src="/resources/scaffold/paginator.xhtml">
				<ui:param name="paginatorBean" value='#{eventBean}'/>
			</ui:include>
		</h:form>
			
	</ui:define>

</ui:composition>

src/main/webapp/event/view.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/resources/scaffold/pageTemplate.xhtml">

	<f:metadata>
		<f:viewParam name="id" value='#{eventBean.id}'/>
		<f:event type="preRenderView" listener='#{eventBean.retrieve}'/>
	</f:metadata>

	<ui:param name="pageTitle" value="View Event"/>

	<ui:define name="header">
		Event
	</ui:define>

	<ui:define name="subheader">
		View existing Event
	</ui:define>

	<ui:define name="footer"/>

	<ui:define name="main">
		<h:panelGrid columnClasses="label,component,required" columns="3">
			<h:outputLabel for="eventBeanEventTitle" value="Title:"/>
			<h:outputText id="eventBeanEventTitle" value="#{eventBean.event.title}"/>
			<h:outputText/>
			<h:outputLabel for="eventBeanEventDescription" value="Description:"/>
			<h:inputTextarea id="eventBeanEventDescription" value="#{eventBean.event.description}"/>
			<h:outputText/>
			<h:outputLabel for="eventBeanEventEBegin" value="E Begin:"/>
			<h:outputText id="eventBeanEventEBegin" value="#{eventBean.event.EBegin}">
				<f:convertDateTime pattern="MMM d, yyyy hh:mm:ss a" type="both"/>
			</h:outputText>
			<h:outputText/>
			<h:outputLabel for="eventBeanEventEEnd" value="E End:"/>
			<h:outputText id="eventBeanEventEEnd" value="#{eventBean.event.EEnd}">
				<f:convertDateTime pattern="MMM d, yyyy hh:mm:ss a" type="both"/>
			</h:outputText>
			<h:outputText/>
			<h:outputLabel for="eventBeanEventAState" value="A State:"/>
			<h:outputText id="eventBeanEventAState" value="#{eventBean.event.AState}"/>
			<h:outputText/>
			<h:outputLabel for="eventBeanEventCDate" value="C Date:"/>
			<h:outputText id="eventBeanEventCDate" value="#{eventBean.event.CDate}">
				<f:convertDateTime pattern="MMM d, yyyy hh:mm:ss a" type="both"/>
			</h:outputText>
			<h:outputText/>
			<h:outputLabel for="eventBeanEventMDate" value="M Date:"/>
			<h:outputText id="eventBeanEventMDate" value="#{eventBean.event.MDate}">
				<f:convertDateTime pattern="MMM d, yyyy hh:mm:ss a" type="both"/>
			</h:outputText>
			<h:outputText/>
			<h:outputLabel for="eventBeanEventPid" value="Pid:"/>
			<h:outputText id="eventBeanEventPid" value="#{eventBean.event.pid}"/>
			<h:outputText/>
		</h:panelGrid>

		<div class="buttons">
			<h:link value="View All" outcome="search" styleClass="btn btn-primary"/> 
			<h:link value="Edit" outcome="create" includeViewParams="true" styleClass="btn btn-primary"/>
			<h:link value="Create New" outcome="create" styleClass="btn btn-primary"/>
		</div>
	</ui:define>

</ui:composition>